namespace WebApplication1.Models
{
    // Customer ID is a GUID generated by the database as defined in the AppDbContext
    // Name is set to empty, but is a required field in the database
    // Address and Phone number are optional
    // The Orders navigation property establishes a one-to-many relationship with the Order entity
    // virtual keyword enables lazy loading of related Order entities if configured in the DbContext

    public class Customer
    {
        public Guid CustomerId { get; set; }
        public string Name { get; set; } = string.Empty;

        public string? Address { get; set; }
        public string? PhoneNumber { get; set; }

        public virtual List<Order> Orders { get; set; } = new List<Order>();
    }

    // -- Comment on Data Annotations -------------------------------------------------
    // I initially added data annotations here but then moved to Fluent Validation to keep validation logic separate from the data model
    //
    // (original comments on useage of Data Annotations are kept below for reference)
    // Data Annotations are used to enforce validation rules on Name and PhoneNumber properties
    // These annotations are used to simplify validation logic in the application layer
    // and return a useful error message if validation fails
    // --------------------------------------------------------------------------------
}
